// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqpikdwbuxnxifgekwqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxcGlrZHdidXhueGlmZ2Vrd3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTI5NjgsImV4cCI6MjA3MjI2ODk2OH0.wFzjreKscPs3jXp4m8KQ0mzMePfdq0rl7TDg7XBLyl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});